# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

class MdmAlertDataType(enum.IntEnum):
    STRING = 0
    BASE64 = 1
    BOOLEAN = 2
    INTEGER = 3

class MdmAlertMark(enum.IntEnum):
    NONE = 0
    FATAL = 1
    CRITICAL = 2
    WARNING = 3
    INFORMATIONAL = 4

class MdmSessionState(enum.IntEnum):
    NOT_STARTED = 0
    STARTING = 1
    CONNECTING = 2
    COMMUNICATING = 3
    ALERT_STATUS_AVAILABLE = 4
    RETRYING = 5
    COMPLETED = 6

class MdmAlert(_winrt.winrt_base):
    ...
    type: str
    target: str
    source: str
    mark: MdmAlertMark
    format: MdmAlertDataType
    data: str
    status: int

class MdmSession(_winrt.winrt_base):
    ...
    alerts: winrt.windows.foundation.collections.IVectorView[MdmAlert]
    extended_error: winrt.windows.foundation.HResult
    id: str
    state: MdmSessionState
    def attach_async() -> winrt.windows.foundation.IAsyncAction:
        ...
    def delete() -> None:
        ...
    def start_async() -> winrt.windows.foundation.IAsyncAction:
        ...
    def start_async(alerts: typing.Iterable[MdmAlert]) -> winrt.windows.foundation.IAsyncAction:
        ...

class MdmSessionManager(_winrt.winrt_base):
    ...
    session_ids: winrt.windows.foundation.collections.IVectorView[str]
    def delete_session_by_id(session_id: str) -> None:
        ...
    def get_session_by_id(session_id: str) -> MdmSession:
        ...
    def try_create_session() -> MdmSession:
        ...

