# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
class PlatformTelemetryRegistrationStatus(enum.IntEnum):
    SUCCESS = 0
    SETTINGS_OUT_OF_RANGE = 1
    UNKNOWN_FAILURE = 2

class PlatformTelemetryClient(_winrt.winrt_base):
    ...
    def register(id: str) -> PlatformTelemetryRegistrationResult:
        ...
    def register(id: str, settings: PlatformTelemetryRegistrationSettings) -> PlatformTelemetryRegistrationResult:
        ...

class PlatformTelemetryRegistrationResult(_winrt.winrt_base):
    ...
    status: PlatformTelemetryRegistrationStatus

class PlatformTelemetryRegistrationSettings(_winrt.winrt_base):
    ...
    upload_quota_size: int
    storage_size: int

