# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.foundation.numerics
except Exception:
    pass

try:
    import winrt.windows.perception.spatial
except Exception:
    pass

class HolographicKeyboard(_winrt.winrt_base):
    ...
    def get_default() -> HolographicKeyboard:
        ...
    def reset_placement_override() -> None:
        ...
    def set_placement_override(coordinate_system: winrt.windows.perception.spatial.SpatialCoordinateSystem, top_center_position: winrt.windows.foundation.numerics.Vector3, orientation: winrt.windows.foundation.numerics.Quaternion) -> None:
        ...
    def set_placement_override(coordinate_system: winrt.windows.perception.spatial.SpatialCoordinateSystem, top_center_position: winrt.windows.foundation.numerics.Vector3, orientation: winrt.windows.foundation.numerics.Quaternion, max_size: winrt.windows.foundation.numerics.Vector2) -> None:
        ...

