# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import winrt

_ns_module = winrt._import_ns_module("Windows.Media.Capture.Core")

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.media.capture
except Exception:
    pass

VariablePhotoCapturedEventArgs = _ns_module.VariablePhotoCapturedEventArgs
VariablePhotoSequenceCapture = _ns_module.VariablePhotoSequenceCapture
