# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

try:
    import winrt.windows.graphics.imaging
except Exception:
    pass

try:
    import winrt.windows.media
except Exception:
    pass

class DetectedFace(_winrt.winrt_base):
    ...
    face_box: winrt.windows.graphics.imaging.BitmapBounds

class FaceDetector(_winrt.winrt_base):
    ...
    min_detectable_face_size: winrt.windows.graphics.imaging.BitmapSize
    max_detectable_face_size: winrt.windows.graphics.imaging.BitmapSize
    is_supported: bool
    def create_async() -> winrt.windows.foundation.IAsyncOperation[FaceDetector]:
        ...
    def detect_faces_async(image: winrt.windows.graphics.imaging.SoftwareBitmap) -> winrt.windows.foundation.IAsyncOperation[winrt.windows.foundation.collections.IVector[DetectedFace]]:
        ...
    def detect_faces_async(image: winrt.windows.graphics.imaging.SoftwareBitmap, search_area: winrt.windows.graphics.imaging.BitmapBounds) -> winrt.windows.foundation.IAsyncOperation[winrt.windows.foundation.collections.IVector[DetectedFace]]:
        ...
    def get_supported_bitmap_pixel_formats() -> winrt.windows.foundation.collections.IVectorView[winrt.windows.graphics.imaging.BitmapPixelFormat]:
        ...
    def is_bitmap_pixel_format_supported(bitmap_pixel_format: winrt.windows.graphics.imaging.BitmapPixelFormat) -> bool:
        ...

class FaceTracker(_winrt.winrt_base):
    ...
    min_detectable_face_size: winrt.windows.graphics.imaging.BitmapSize
    max_detectable_face_size: winrt.windows.graphics.imaging.BitmapSize
    is_supported: bool
    def create_async() -> winrt.windows.foundation.IAsyncOperation[FaceTracker]:
        ...
    def get_supported_bitmap_pixel_formats() -> winrt.windows.foundation.collections.IVectorView[winrt.windows.graphics.imaging.BitmapPixelFormat]:
        ...
    def is_bitmap_pixel_format_supported(bitmap_pixel_format: winrt.windows.graphics.imaging.BitmapPixelFormat) -> bool:
        ...
    def process_next_frame_async(video_frame: winrt.windows.media.VideoFrame) -> winrt.windows.foundation.IAsyncOperation[winrt.windows.foundation.collections.IVector[DetectedFace]]:
        ...

