# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum

import winrt

_ns_module = winrt._import_ns_module("Windows.UI.UIAutomation.Core")

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.ui.uiautomation
except Exception:
    pass

class AutomationRemoteOperationStatus(enum.IntEnum):
    SUCCESS = 0
    MALFORMED_BYTECODE = 1
    INSTRUCTION_LIMIT_EXCEEDED = 2
    UNHANDLED_EXCEPTION = 3
    EXECUTION_FAILURE = 4

AutomationAnnotationTypeRegistration = _ns_module.AutomationAnnotationTypeRegistration
AutomationRemoteOperationOperandId = _ns_module.AutomationRemoteOperationOperandId
AutomationRemoteOperationResult = _ns_module.AutomationRemoteOperationResult
CoreAutomationRegistrar = _ns_module.CoreAutomationRegistrar
CoreAutomationRemoteOperation = _ns_module.CoreAutomationRemoteOperation
CoreAutomationRemoteOperationContext = _ns_module.CoreAutomationRemoteOperationContext
RemoteAutomationClientSession = _ns_module.RemoteAutomationClientSession
RemoteAutomationConnectionRequestedEventArgs = _ns_module.RemoteAutomationConnectionRequestedEventArgs
RemoteAutomationDisconnectedEventArgs = _ns_module.RemoteAutomationDisconnectedEventArgs
RemoteAutomationServer = _ns_module.RemoteAutomationServer
RemoteAutomationWindow = _ns_module.RemoteAutomationWindow
ICoreAutomationConnectionBoundObjectProvider = _ns_module.ICoreAutomationConnectionBoundObjectProvider
ICoreAutomationRemoteOperationExtensionProvider = _ns_module.ICoreAutomationRemoteOperationExtensionProvider
