# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum

import winrt

_ns_module = winrt._import_ns_module("Windows.Services.Maps.LocalSearch")

try:
    import winrt.windows.devices.geolocation
except Exception:
    pass

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

try:
    import winrt.windows.globalization
except Exception:
    pass

try:
    import winrt.windows.services.maps
except Exception:
    pass

class LocalLocationFinderStatus(enum.IntEnum):
    SUCCESS = 0
    UNKNOWN_ERROR = 1
    INVALID_CREDENTIALS = 2
    INVALID_CATEGORY = 3
    INVALID_SEARCH_TERM = 4
    INVALID_SEARCH_AREA = 5
    NETWORK_FAILURE = 6
    NOT_SUPPORTED = 7

LocalCategories = _ns_module.LocalCategories
LocalLocation = _ns_module.LocalLocation
LocalLocationFinder = _ns_module.LocalLocationFinder
LocalLocationFinderResult = _ns_module.LocalLocationFinderResult
LocalLocationHoursOfOperationItem = _ns_module.LocalLocationHoursOfOperationItem
LocalLocationRatingInfo = _ns_module.LocalLocationRatingInfo
PlaceInfoHelper = _ns_module.PlaceInfoHelper
