# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import winrt

_ns_module = winrt._import_ns_module("Windows.Web.AtomPub")

try:
    import winrt.windows.data.xml.dom
except Exception:
    pass

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

try:
    import winrt.windows.security.credentials
except Exception:
    pass

try:
    import winrt.windows.storage.streams
except Exception:
    pass

try:
    import winrt.windows.web.syndication
except Exception:
    pass

AtomPubClient = _ns_module.AtomPubClient
ResourceCollection = _ns_module.ResourceCollection
ServiceDocument = _ns_module.ServiceDocument
Workspace = _ns_module.Workspace
