# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

class EnterpriseKeyCredentialRegistrationInfo(_winrt.winrt_base):
    ...
    key_id: str
    key_name: str
    subject: str
    tenant_id: str
    tenant_name: str

class EnterpriseKeyCredentialRegistrationManager(_winrt.winrt_base):
    ...
    current: EnterpriseKeyCredentialRegistrationManager
    def get_registrations_async() -> winrt.windows.foundation.IAsyncOperation[winrt.windows.foundation.collections.IVectorView[EnterpriseKeyCredentialRegistrationInfo]]:
        ...

