# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum

import winrt

_ns_module = winrt._import_ns_module("Windows.Management.Policies")

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.storage.streams
except Exception:
    pass

try:
    import winrt.windows.system
except Exception:
    pass

class NamedPolicyKind(enum.IntEnum):
    INVALID = 0
    BINARY = 1
    BOOLEAN = 2
    INT32 = 3
    INT64 = 4
    STRING = 5

NamedPolicy = _ns_module.NamedPolicy
NamedPolicyData = _ns_module.NamedPolicyData
