# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.devices.sensors
except Exception:
    pass

try:
    import winrt.windows.foundation
except Exception:
    pass

class HingeState(enum.IntEnum):
    UNKNOWN = 0
    CLOSED = 1
    CONCAVE = 2
    FLAT = 3
    CONVEX = 4
    FULL = 5

class TwoPanelHingedDevicePosturePreview(_winrt.winrt_base):
    ...
    def get_current_posture_async() -> winrt.windows.foundation.IAsyncOperation[TwoPanelHingedDevicePosturePreviewReading]:
        ...
    def get_default_async() -> winrt.windows.foundation.IAsyncOperation[TwoPanelHingedDevicePosturePreview]:
        ...
    def add_posture_changed(handler: winrt.windows.foundation.TypedEventHandler[TwoPanelHingedDevicePosturePreview, TwoPanelHingedDevicePosturePreviewReadingChangedEventArgs]) -> winrt.windows.foundation.EventRegistrationToken:
        ...
    def remove_posture_changed(token: winrt.windows.foundation.EventRegistrationToken) -> None:
        ...

class TwoPanelHingedDevicePosturePreviewReading(_winrt.winrt_base):
    ...
    hinge_state: HingeState
    panel1_id: str
    panel1_orientation: winrt.windows.devices.sensors.SimpleOrientation
    panel2_id: str
    panel2_orientation: winrt.windows.devices.sensors.SimpleOrientation
    timestamp: winrt.windows.foundation.DateTime

class TwoPanelHingedDevicePosturePreviewReadingChangedEventArgs(_winrt.winrt_base):
    ...
    reading: TwoPanelHingedDevicePosturePreviewReading

