# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

try:
    import winrt.windows.media.core
except Exception:
    pass

try:
    import winrt.windows.media.mediaproperties
except Exception:
    pass

try:
    import winrt.windows.storage
except Exception:
    pass

try:
    import winrt.windows.storage.streams
except Exception:
    pass

class MediaVideoProcessingAlgorithm(enum.IntEnum):
    DEFAULT = 0
    MRF_CRF444 = 1

class TranscodeFailureReason(enum.IntEnum):
    NONE = 0
    UNKNOWN = 1
    INVALID_PROFILE = 2
    CODEC_NOT_FOUND = 3

class MediaTranscoder(_winrt.winrt_base):
    ...
    trim_stop_time: winrt.windows.foundation.TimeSpan
    trim_start_time: winrt.windows.foundation.TimeSpan
    hardware_acceleration_enabled: bool
    always_reencode: bool
    video_processing_algorithm: MediaVideoProcessingAlgorithm
    def add_audio_effect(activatable_class_id: str) -> None:
        ...
    def add_audio_effect(activatable_class_id: str, effect_required: bool, configuration: winrt.windows.foundation.collections.IPropertySet) -> None:
        ...
    def add_video_effect(activatable_class_id: str) -> None:
        ...
    def add_video_effect(activatable_class_id: str, effect_required: bool, configuration: winrt.windows.foundation.collections.IPropertySet) -> None:
        ...
    def clear_effects() -> None:
        ...
    def prepare_file_transcode_async(source: winrt.windows.storage.IStorageFile, destination: winrt.windows.storage.IStorageFile, profile: winrt.windows.media.mediaproperties.MediaEncodingProfile) -> winrt.windows.foundation.IAsyncOperation[PrepareTranscodeResult]:
        ...
    def prepare_media_stream_source_transcode_async(source: winrt.windows.media.core.IMediaSource, destination: winrt.windows.storage.streams.IRandomAccessStream, profile: winrt.windows.media.mediaproperties.MediaEncodingProfile) -> winrt.windows.foundation.IAsyncOperation[PrepareTranscodeResult]:
        ...
    def prepare_stream_transcode_async(source: winrt.windows.storage.streams.IRandomAccessStream, destination: winrt.windows.storage.streams.IRandomAccessStream, profile: winrt.windows.media.mediaproperties.MediaEncodingProfile) -> winrt.windows.foundation.IAsyncOperation[PrepareTranscodeResult]:
        ...

class PrepareTranscodeResult(_winrt.winrt_base):
    ...
    can_transcode: bool
    failure_reason: TranscodeFailureReason
    def transcode_async() -> winrt.windows.foundation.IAsyncActionWithProgress[float]:
        ...

