# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import typing
import uuid

import winrt._winrt as _winrt
class HtmlUtilities(_winrt.winrt_base):
    ...
    def convert_to_text(html: str) -> str:
        ...

