# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.ui.text
except Exception:
    pass

class LanguageFont(_winrt.winrt_base):
    ...
    font_family: str
    font_stretch: winrt.windows.ui.text.FontStretch
    font_style: winrt.windows.ui.text.FontStyle
    font_weight: winrt.windows.ui.text.FontWeight
    scale_factor: float

class LanguageFontGroup(_winrt.winrt_base):
    ...
    document_alternate1_font: LanguageFont
    document_alternate2_font: LanguageFont
    document_heading_font: LanguageFont
    fixed_width_text_font: LanguageFont
    modern_document_font: LanguageFont
    traditional_document_font: LanguageFont
    u_i_caption_font: LanguageFont
    u_i_heading_font: LanguageFont
    u_i_notification_heading_font: LanguageFont
    u_i_text_font: LanguageFont
    u_i_title_font: LanguageFont

