# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
class MessagingSyncPolicy(enum.IntEnum):
    DISALLOWED = 0
    ALLOWED = 1
    REQUIRED = 2

class MdmPolicy(_winrt.winrt_base):
    ...
    def get_messaging_sync_policy() -> MessagingSyncPolicy:
        ...
    def is_browser_allowed() -> bool:
        ...
    def is_camera_allowed() -> bool:
        ...
    def is_microsoft_account_allowed() -> bool:
        ...
    def is_store_allowed() -> bool:
        ...

