# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import winrt

_ns_module = winrt._import_ns_module("Windows.ApplicationModel.Payments.Provider")

try:
    import winrt.windows.applicationmodel.payments
except Exception:
    pass

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

PaymentAppCanMakePaymentTriggerDetails = _ns_module.PaymentAppCanMakePaymentTriggerDetails
PaymentAppManager = _ns_module.PaymentAppManager
PaymentTransaction = _ns_module.PaymentTransaction
PaymentTransactionAcceptResult = _ns_module.PaymentTransactionAcceptResult
