# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.applicationmodel.datatransfer
except Exception:
    pass

try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

try:
    import winrt.windows.storage.streams
except Exception:
    pass

try:
    import winrt.windows.system
except Exception:
    pass

class CortanaPermission(enum.IntEnum):
    BROWSING_HISTORY = 0
    CALENDAR = 1
    CALL_HISTORY = 2
    CONTACTS = 3
    EMAIL = 4
    INPUT_PERSONALIZATION = 5
    LOCATION = 6
    MESSAGING = 7
    MICROPHONE = 8
    PERSONALIZATION = 9
    PHONE_CALL = 10

class CortanaPermissionsChangeResult(enum.IntEnum):
    SUCCESS = 0
    UNAVAILABLE = 1
    DISABLED_BY_POLICY = 2

class CortanaActionableInsights(_winrt.winrt_base):
    ...
    user: winrt.windows.system.User
    def get_default() -> CortanaActionableInsights:
        ...
    def get_for_user(user: winrt.windows.system.User) -> CortanaActionableInsights:
        ...
    def is_available_async() -> winrt.windows.foundation.IAsyncOperation[bool]:
        ...
    def show_insights_async(datapackage: winrt.windows.applicationmodel.datatransfer.DataPackage) -> winrt.windows.foundation.IAsyncAction:
        ...
    def show_insights_async(datapackage: winrt.windows.applicationmodel.datatransfer.DataPackage, options: CortanaActionableInsightsOptions) -> winrt.windows.foundation.IAsyncAction:
        ...
    def show_insights_for_image_async(image_stream: winrt.windows.storage.streams.IRandomAccessStreamReference) -> winrt.windows.foundation.IAsyncAction:
        ...
    def show_insights_for_image_async(image_stream: winrt.windows.storage.streams.IRandomAccessStreamReference, options: CortanaActionableInsightsOptions) -> winrt.windows.foundation.IAsyncAction:
        ...
    def show_insights_for_text_async(text: str) -> winrt.windows.foundation.IAsyncAction:
        ...
    def show_insights_for_text_async(text: str, options: CortanaActionableInsightsOptions) -> winrt.windows.foundation.IAsyncAction:
        ...

class CortanaActionableInsightsOptions(_winrt.winrt_base):
    ...
    surrounding_text: str
    content_source_web_link: winrt.windows.foundation.Uri

class CortanaPermissionsManager(_winrt.winrt_base):
    ...
    def are_permissions_granted_async(permissions: typing.Iterable[CortanaPermission]) -> winrt.windows.foundation.IAsyncOperation[bool]:
        ...
    def get_default() -> CortanaPermissionsManager:
        ...
    def grant_permissions_async(permissions: typing.Iterable[CortanaPermission]) -> winrt.windows.foundation.IAsyncOperation[CortanaPermissionsChangeResult]:
        ...
    def is_supported() -> bool:
        ...
    def revoke_permissions_async(permissions: typing.Iterable[CortanaPermission]) -> winrt.windows.foundation.IAsyncOperation[CortanaPermissionsChangeResult]:
        ...

class CortanaSettings(_winrt.winrt_base):
    ...
    is_voice_activation_enabled: bool
    has_user_consent_to_voice_activation: bool
    def get_default() -> CortanaSettings:
        ...
    def is_supported() -> bool:
        ...

