# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import typing
import uuid

import winrt._winrt as _winrt
class IGraphicsEffect(IGraphicsEffectSource, _winrt.winrt_base):
    ...
    name: str

class IGraphicsEffectSource(_winrt.winrt_base):
    ...

