# WARNING: Please don't edit this file. It was generated by Python/WinRT v1.2.3.4

import enum
import typing
import uuid

import winrt._winrt as _winrt
try:
    import winrt.windows.foundation
except Exception:
    pass

try:
    import winrt.windows.foundation.collections
except Exception:
    pass

try:
    import winrt.windows.graphics.printing
except Exception:
    pass

try:
    import winrt.windows.storage.streams
except Exception:
    pass

class PrintOptionStates(enum.IntFlag):
    NONE = 0
    ENABLED = 0x1
    CONSTRAINED = 0x2

class PrintOptionType(enum.IntEnum):
    UNKNOWN = 0
    NUMBER = 1
    TEXT = 2
    ITEM_LIST = 3
    TOGGLE = 4

class PrintBindingOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintBorderingOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintCollationOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintColorModeOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintCopiesOptionDetails(IPrintOptionDetails, IPrintNumberOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    max_value: int
    min_value: int
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintCustomItemDetails(_winrt.winrt_base):
    ...
    item_display_name: str
    item_id: str

class PrintCustomItemListOptionDetails(IPrintOptionDetails, IPrintCustomOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    display_name: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def add_item(item_id: str, display_name: str) -> None:
        ...
    def add_item(item_id: str, display_name: str, description: str, icon: winrt.windows.storage.streams.IRandomAccessStreamWithContentType) -> None:
        ...
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintCustomTextOptionDetails(IPrintOptionDetails, IPrintCustomOptionDetails, _winrt.winrt_base):
    ...
    display_name: str
    max_characters: int
    warning_text: str
    description: str
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintCustomToggleOptionDetails(IPrintOptionDetails, IPrintCustomOptionDetails, _winrt.winrt_base):
    ...
    display_name: str
    warning_text: str
    description: str
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintDuplexOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintHolePunchOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    warning_text: str
    description: str
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintMediaSizeOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    warning_text: str
    description: str
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintMediaTypeOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    warning_text: str
    description: str
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintOrientationOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    warning_text: str
    description: str
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintPageRangeOptionDetails(IPrintOptionDetails, _winrt.winrt_base):
    ...
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    warning_text: str
    description: str
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintQualityOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    warning_text: str
    description: str
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintStapleOptionDetails(IPrintOptionDetails, IPrintItemListOptionDetails, _winrt.winrt_base):
    ...
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    state: PrintOptionStates
    error_text: str
    option_id: str
    option_type: PrintOptionType
    value: _winrt.winrt_base
    warning_text: str
    description: str
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class PrintTaskOptionChangedEventArgs(_winrt.winrt_base):
    ...
    option_id: _winrt.winrt_base

class PrintTaskOptionDetails(winrt.windows.graphics.printing.IPrintTaskOptionsCore, winrt.windows.graphics.printing.IPrintTaskOptionsCoreUIConfiguration, _winrt.winrt_base):
    ...
    displayed_options: winrt.windows.foundation.collections.IVector[str]
    options: winrt.windows.foundation.collections.IMapView[str, IPrintOptionDetails]
    def create_item_list_option(option_id: str, display_name: str) -> PrintCustomItemListOptionDetails:
        ...
    def create_text_option(option_id: str, display_name: str) -> PrintCustomTextOptionDetails:
        ...
    def create_toggle_option(option_id: str, display_name: str) -> PrintCustomToggleOptionDetails:
        ...
    def get_from_print_task_options(print_task_options: winrt.windows.graphics.printing.PrintTaskOptions) -> PrintTaskOptionDetails:
        ...
    def get_page_description(job_page_number: int) -> winrt.windows.graphics.printing.PrintPageDescription:
        ...
    def add_begin_validation(event_handler: winrt.windows.foundation.TypedEventHandler[PrintTaskOptionDetails, _winrt.winrt_base]) -> winrt.windows.foundation.EventRegistrationToken:
        ...
    def remove_begin_validation(event_cookie: winrt.windows.foundation.EventRegistrationToken) -> None:
        ...
    def add_option_changed(event_handler: winrt.windows.foundation.TypedEventHandler[PrintTaskOptionDetails, PrintTaskOptionChangedEventArgs]) -> winrt.windows.foundation.EventRegistrationToken:
        ...
    def remove_option_changed(event_cookie: winrt.windows.foundation.EventRegistrationToken) -> None:
        ...

class IPrintCustomOptionDetails(IPrintOptionDetails, _winrt.winrt_base):
    ...
    display_name: str
    error_text: str
    option_id: str
    option_type: PrintOptionType
    state: PrintOptionStates
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class IPrintItemListOptionDetails(IPrintOptionDetails, _winrt.winrt_base):
    ...
    items: winrt.windows.foundation.collections.IVectorView[_winrt.winrt_base]
    error_text: str
    option_id: str
    option_type: PrintOptionType
    state: PrintOptionStates
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class IPrintNumberOptionDetails(IPrintOptionDetails, _winrt.winrt_base):
    ...
    max_value: int
    min_value: int
    error_text: str
    option_id: str
    option_type: PrintOptionType
    state: PrintOptionStates
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class IPrintOptionDetails(_winrt.winrt_base):
    ...
    error_text: str
    option_id: str
    option_type: PrintOptionType
    state: PrintOptionStates
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

class IPrintTextOptionDetails(IPrintOptionDetails, _winrt.winrt_base):
    ...
    max_characters: int
    error_text: str
    option_id: str
    option_type: PrintOptionType
    state: PrintOptionStates
    value: _winrt.winrt_base
    def try_set_value(value: _winrt.winrt_base) -> bool:
        ...

